/// Flutter icons MyFlutterApp
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MyFlutterApp
///      fonts:
///       - asset: fonts/MyFlutterApp.ttf
///
/// 
/// * Modern Pictograms, Copyright (c) 2012 by John Caserta. All rights reserved.
///         Author:    John Caserta
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://thedesignoffice.org/project/modern-pictograms/
///
import 'package:flutter/widgets.dart';

class MyFlutterApp {
  MyFlutterApp._();

  static const _kFontFam = 'AthenaIcon';
  static const String _kFontPkg = null;

  static const IconData bullhorn = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData loudspeaker = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData scanner = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
